import { Injectable, Logger, OnModuleInit } from '@nestjs/common';
import { Queue, Worker } from 'bullmq';
import { PrismaService } from '../../prisma/prisma.service';
import { DOMAIN_EVENTS } from '../../events/event.types';
import { NotificationsService } from '../notifications.service';
import { ReceiptService } from '../../payments/receipts/receipt.service';

/**
 * Consumes `PAYMENT_VALIDATED` and notifies the tenant that their
 * receipt is ready.
 *
 * The receipt itself is generated by `PaymentValidatedProcessor` in the
 * payments module; here we just look up its URL and send a WhatsApp
 * message via `NotificationsService`. We avoid double-generating by
 * keying off the existing Receipt row.
 */
@Injectable()
export class PaymentValidatedProcessor implements OnModuleInit {
  private readonly logger = new Logger(PaymentValidatedProcessor.name);
  private worker!: Worker;

  constructor(
    private readonly prisma: PrismaService,
    private readonly notifications: NotificationsService,
    private readonly receipts: ReceiptService,
  ) {}

  onModuleInit(): Promise<void> {
    if (!process.env.REDIS_URL) {
      this.logger.warn(
        'REDIS_URL not set — skipping PAYMENT_VALIDATED notification processor',
      );
      return Promise.resolve();
    }
    const u = new URL(process.env.REDIS_URL);
    const connection = {
      host: u.hostname || 'localhost',
      port: Number(u.port || 6379),
      ...(u.password ? { password: decodeURIComponent(u.password) } : {}),
    };

    // No producer needed — the events are emitted by the payments service.
    void new Queue(DOMAIN_EVENTS.PAYMENT_VALIDATED, { connection });

    this.worker = new Worker(
      DOMAIN_EVENTS.PAYMENT_VALIDATED,
      async (job) => {
        const payload = (job.data as { payload?: unknown }).payload as
          { paymentId: string; userId: string } | undefined;
        if (!payload?.paymentId) {
          this.logger.warn(`PAYMENT_VALIDATED job ${job.id} missing paymentId`);
          return { skipped: true };
        }
        return this.handlePaymentValidated(payload.paymentId, payload.userId);
      },
      { connection },
    );
    return Promise.resolve();
  }

  /**
   * Public for direct invocation from tests — no BullMQ dependency.
   */
  async handlePaymentValidated(
    paymentId: string,
    _userId: string,
  ): Promise<{ sent: boolean; reason?: string }> {
    // _userId is the event's userId; the canonical recipient is read
    // from the payment row itself (avoids divergence if the event was
    // emitted for a different actor).
    void _userId;
    // The receipts processor may not have run yet — generate now so the
    // notification always points at a real URL.
    const receipt = await this.receipts.generateForPayment(paymentId);
    const payment = await this.prisma.payment.findUnique({
      where: { id: paymentId },
      select: { userId: true },
    });
    if (!payment) {
      this.logger.warn(`Payment ${paymentId} not found for notification`);
      return { sent: false, reason: 'PAYMENT_NOT_FOUND' };
    }
    const result = await this.notifications.send({
      userId: payment.userId,
      channel: 'WHATSAPP',
      type: 'PAYMENT_RECEIPT_READY',
      payload: {
        paymentId,
        receiptUrl: receipt.url,
        receiptNumber: receipt.number,
      },
    });
    this.logger.log(
      `Notified user ${payment.userId} about receipt ${receipt.number} (status=${result.status})`,
    );
    return { sent: result.status === 'SENT' };
  }
}
